# permissions for end users to view extensions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extension-viewer-role
rules:
- apiGroups:
  - dynatrace.com
  resources:
  - extensions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dynatrace.com
  resources:
  - extensions/status
  verbs:
  - get
