# permissions for end users to edit extensions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extension-editor-role
rules:
- apiGroups:
  - dynatrace.com
  resources:
  - extensions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynatrace.com
  resources:
  - extensions/status
  verbs:
  - get
