apiVersion: dynatrace.com/v1alpha1
kind: Extension
metadata:
  name: extension-sample
  namespace: dt-extensions
spec:
  extensions:
    - name: rabbitmq
      downloadLink: http://192.168.15.101:5656/custom.python.rabbitmq_kubernetes.zip
    - name: redis
      downloadLink: http://192.168.15.101:5656/custom.python.redis_kubernetes.zip

